repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-added-large-files
        exclude: "^assets/"
      - id: check-docstring-first
      - id: debug-statements
      - id: end-of-file-fixer
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: debug-statements
      - id: detect-private-key
      - id: trailing-whitespace
        exclude: "^docs/"
      - id: mixed-line-ending
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
      - id: pyupgrade
        args: [--py310-plus]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.6.3"
    hooks:
      - id: ruff
        types_or: [python, pyi, jupyter, toml]
        args: [--fix]
      - id: ruff-format
        types_or: [python, pyi, jupyter, toml]

  - repo: https://github.com/thibaudcolas/pre-commit-stylelint
    rev: v14.4.0
    hooks:
      - id: stylelint
        files: \.(css|scss|sass|less)$
        types: [file]
        additional_dependencies:
          - stylelint@^15.0.0
          - stylelint-config-standard@^34.0.0

  - repo: https://github.com/biomejs/pre-commit
    rev: v2.2.2
    hooks:
      - id: biome-check
