repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-added-large-files
        exclude: "^assets/"
      - id: check-docstring-first
      - id: debug-statements
      - id: end-of-file-fixer
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: debug-statements
      - id: detect-private-key
      - id: trailing-whitespace
        exclude: "^docs/"
      - id: mixed-line-ending
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
      - id: pyupgrade
        args: [--py310-plus]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.6.3"
    hooks:
      - id: ruff
        types_or: [python, pyi, jupyter, toml]
        args: [--fix]
      - id: ruff-format
        types_or: [python, pyi, jupyter, toml]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.3"
    hooks:
      - id: prettier

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.57.0
    hooks:
      - id: eslint
        files: \.(js|jsx|ts|tsx)$
        types: [file]
        additional_dependencies:
          - eslint@^8.0.0
          - "@typescript-eslint/parser@^6.0.0"
          - "@typescript-eslint/eslint-plugin@^6.0.0"

  - repo: https://github.com/pre-commit/mirrors-stylelint
    rev: v15.10.3
    hooks:
      - id: stylelint
        files: \.(css|scss|sass|less)$
        types: [file]
        additional_dependencies:
          - stylelint@^15.0.0
          - stylelint-config-standard@^34.0.0

  - repo: https://github.com/pre-commit/mirrors-htmlhint
    rev: v1.1.4
    hooks:
      - id: htmlhint
        files: \.(html|htm)$
        types: [file]
